apiVersion: v2
name: cryptobalancer
description: A Helm chart for the CryptoBalancer Platform

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: "0.1.0"
    repository: "file://../frontend"
  - name: backend
    version: "0.1.0"
    repository: "file://../backend"
  - name: cert-manager
    version: "0.1.0"
    repository: "file://../cert-manager"
    condition: cert-manager.enabled
